name: curved_navigation_bar_with_label
description: Stunning Animating Curved Shape Navigation Bar. Adjustable color, background color, animation curve, animation duration, with label.
version: 2.1.0
homepage: https://github.com/ARASHz4/curved_navigation_bar_with_label

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
